server:
  port: 8080
server.servlet.context-path: /
name: 蒲浦甫
age: 25


spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/webapp/html/
      suffix: .html
#  view:
#    prefix: /static/webapp/jsp/
#    suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: update




mybatis:
  typeAliasesPackage: com.ppf.springboot.entity
  mapperLocations: classpath:mybatis/*.xml

  #设置热部署生效
  #spring.devtools.restart.enabled: true
  #设置重启的目录，添加那个目录的文件需要restart
  #spring.devtools.restart.additional-paths: src/main/java
  #排除那个目录的文件不需要restart
  #spring.devtools.restart.exclude: static/**,public/**
  #classpath的目录下的WEB-INF文件夹内容修改不重启
  #spring.devtools.restart.exclude: WEB-INF/**


